name: DasLoch
version: ${version}
main: de.opalium.dasloch.DasLochPlugin
api-version: '1.21'

description: Core plugin for DasLoch mystic & legend items, well system and combat features.
authors:
  - Opalium

github-repo: "DemusOpalium/opalium-mystic"

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  dasloch:
    description: Admin command for DasLoch plugin utilities
    usage: "/dasloch <reload|debug|well|legend|mystic> ..."
    aliases: [dl]
    permission: dasloch.use

  mysticwell:
    description: Access the mystic well for rolling mystic items
    aliases: [well]
    usage: "/mysticwell [roll <tier> [player]]"
    permission: dasloch.well

permissions:
  dasloch.use:
    description: Allows use of the /dasloch admin command
    default: op

  dasloch.legend.give:
    description: Allows giving legend items with /dasloch legend ...
    default: op

  dasloch.mystic.give:
    description: Allows giving mystic items with /dasloch mystic ...
    default: op

  dasloch.well:
    description: Allows access to the mystic well command
    default: true
