name: DasLoch
version: ${version}
main: de.opalium.dasloch.DasLochPlugin
api-version: '1.21'
authors:
  - Opalium
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  dasloch:
    description: Main command for DasLoch plugin utilities
    usage: /<command> <reload|debug>
    permission: dasloch.use
  legendgive:
    description: Gives a configured legend item to a player
    usage: /<command> <id> <player>
    permission: dasloch.legend
  mysticgive:
    description: Gives a configured mystic item to a player
    usage: /<command> <id> <player>
    permission: dasloch.mystic
  mysticwell:
    description: Access the mystic well for rolling mystic items
    aliases: [well]
    usage: /<command> [roll <tier> [player]]
    permission: dasloch.well

permissions:
  dasloch.well:
    description: Allows access to the mystic well command
    default: true
